### ISSUE TITLE
作者你好，我这边测试遇到一个问题

### ISSUE THREAD

**Issue by nxnyk** [kongzue/Tabbar#2]
就是在5.1.1版本的手机上，会出现tabbar不会跟着变的情况。机型是vivo x7 plus,选中第二个tab，任然是第一个tab上进行了染色，没有反应

**Comment by kongzue** [comment]
您好，Demo也是出现这个问题么？

**Comment by nxnyk** [comment]
> 您好，Demo也是出现这个问题么？

Demo也是，只有文字的颜色变，图标的颜色不会变，切换别的tab，所有的tab颜色都变成无色的，只有文字是蓝色的，二套图的没问题

**Comment by nxnyk** [comment]
![image](https://user-images.githubusercontent.com/42330422/48681190-e0ff6800-ebdb-11e8-8e66-8297a8d9ea01.png)

**Comment by kongzue** [comment]
好的，这个我会查一下是怎么回事

**Comment by nxnyk** [comment]
> 好的，这个我会查一下是怎么回事
好的，麻烦了

**Comment by kongzue** [comment]
请更新至 1.5.1 版本

**Comment by nxnyk** [comment]
> 请更新至 1.5.1 版本

好的，谢谢作者

**Comment by nxnyk** [comment]
> 请更新至 1.5.1 版本

作者，我发现好像normalcolor这个属性没用了对图标无效，只有对文字有效，你看一下，拜托了

**Comment by nxnyk** [comment]
> > 请更新至 1.5.1 版本
> 
> 作者，我发现好像normalcolor这个属性没用了对图标无效，只有对文字有效，你看一下，拜托了

![image](https://user-images.githubusercontent.com/42330422/48756260-64e84b80-ecd3-11e8-89d8-f2a0752571b5.png)

**Comment by kongzue** [comment]
请更新至 1.5.2 版本

**Comment by nxnyk** [comment]
> 请更新至 1.5.2 版本

ok，解决了，谢谢
