### ISSUE TITLE
请求接口后更新未读数量不起作用

### ISSUE THREAD

**Issue by parade0393** [kongzue/Tabbar#7]
未读数量是要从接口获取的，在项目中在接口返回数据后更新未读数量不起作用。
我在demo里模拟了请求更新，同样也不起作用，是我的使用姿势不对吗，大佬。
demo里这样添加的模拟

```java
new Handler().postDelayed(new Runnable() {
    @Override
    public void run() {
       runOnUiThread(new Runnable() {
           @Override
           public void run() {
               myTabbar.setUnreadNum(0,2);
           }
       });
    }
}, 2000);
```

项目中这样使用

```java
NetWork.getOaService().getCountByUserId()
        .subscribeOn(Schedulers.io())
        .observeOn(AndroidSchedulers.mainThread())
        .subscribe(new BaseSubscriber<MessageVO>(MainActivity.this){
            @Override
            public void onNext(MessageVO messageVO) {
                TLog.d("initMessageCount::"+messageVO.getValue());
                tabBarView.setUnreadNum(1,Integer.parseInt(messageVO.getValue()));
                // countViewModel.getMessageCount().setValue(Integer.parseInt(messageVO.getValue()));
            }
        });
```

**Comment by nxnyk** [comment]
看下源码就知道了  设置未读消息的时候偏移量设置错了
![image](https://user-images.githubusercontent.com/42330422/83861794-a1fc1d80-a753-11ea-80b6-7ef07a718683.png)

**Comment by parade0393** [comment]
但是从其它页面返回，这样设置是没问题的。我想可能是绘制问题，就把源码download下来，在setUnreadNumber()最后加了postInvalidate()和requestLayout()也没有作用

**Comment by nxnyk** [comment]
> 但是从其它页面返回，这样设置是没问题的。我想可能是绘制问题，就把源码download下来，在setUnreadNumber()最后加了postInvalidate()和requestLayout()也没有作用

那是因为还没绘制完成，宽度返回的0的原因吧？你把我圈出来那部分删了试试

**Comment by parade0393** [comment]
删了没问题，但是绘制完再调用还是有问题的

**Comment by nxnyk** [comment]
> 删了没问题，但是绘制完再调用还是有问题的

搞定了吗

**Comment by kongzue** [comment]
> 看下源码就知道了 设置未读消息的时候偏移量设置错了
> ![image](https://user-images.githubusercontent.com/42330422/83861794-a1fc1d80-a753-11ea-80b6-7ef07a718683.png)

没道理啊，一般网络请求完这个布局早渲染完了，此时getWidth不可能为0
